New questions louis and bug fix
Dromadon/gennaker pull request #10
Opened 2023-07-24 09:27 UTC by LouisValery

Branch à merge après verification

2023-07-25 19:21 UTC, Dromadon commented
OK pour intégrer la feature branch

2023-07-25 19:21 UTC, Dromadon submitted a review, later dismissed

2023-07-25 20:25 UTC, Dromadon requested changes
Je viens de tout relire !

J'ai poussé 2 commits pour rendre le support Windsurf sélectionnable sur la page principale, et mettre le contenu des évaluations en phase avec les nouvelles sections météo.

Sinon dans l'essentiel je te propose quelques corrections de typos, une ou deux sur le fond (notamment sur le vrillage ?) et une sur l'affichage des images :+1: 

Si tu veux qu'on se refasse un appel jeudi, je suis dispo.

2023-07-25 20:25 UTC, Dromadon commented on public/questions/oceanographie/maree/sonde_negative.md
> +# Que signifie un chiffre souligné sur une carte marine?
Pour le coup je mettrais bien ces questions sur les cartes dans la Catégorie Navigation

2023-07-25 20:25 UTC, Dromadon commented on public/questions/oceanographie/maree/sonde_negative.md
> +# Que signifie un chiffre souligné sur une carte marine?
Par exemple en ajoutant une section (il y a déjà alignement et balisage)

2023-07-25 20:25 UTC, Dromadon commented on public/questions/meteo/carte_meteo/lecture_carte.md
> +<small>Source : [*Cours théorique planche à voile*, Les Glénans CEB, 2023](https://encadrementbenevole.glenans.asso.fr/wp-content/uploads/2023/07/Cours-theorique-PAV-Version-1.pdf) </small>
Que sont les trois points noirs sur la carte ?

2023-07-25 20:25 UTC, Dromadon commented on public/questions/meteo/carte_meteo/definition_front_froid.md
> +![image_correction](./images/front_froid_schema.png)
L'image ne s'affiche pas, il faut avoir comme path `images/front_froid_schema.png` sans le `./`

Il faut passer la correction sur toutes les images ajoutées (si tu galères dis-moi et je le ferai à grand coup de regex)

2023-07-26 08:23 UTC, LouisValery commented on public/questions/meteo/perturbation/passage_perturbation.md
> +# Correction
tu ne parles pas de celui affiché dans la correction? ou tu veux un schéma vu du haut

2023-07-26 08:39 UTC, LouisValery commented on public/questions/fonctionnement_engin/divers/vrillage.md
> +Souvent, on explique que la voile s’adapte localement à la vitesse du vent synoptique, mais ceci n’est vrai que pour les voiliers dont le mât dépasse les 30 mètres. En voile légère il n’y a de variat
J'ai rajouté, mais pas très convaincu par l'explication avec le foc...

2023-07-26 08:46 UTC, LouisValery commented on public/questions/fonctionnement_engin/reglage/VL/windsurf/creux_voile_minimum.md
> +Une voile à besoin d'un creux pour fonctionner. Il est important de garder un creux bien défini, sinon il risque de se déplacer au gré des rafales d’avant en arrière ce qui rend la voile incontrôlabl
si ta voile est plate le creux se ballade d'avant en arrière sans prévenir, à la moindre sollicitation. C'est un peu comme passer son doigt sur une bâche tendu: peu importe où tu appuis, tu forme un creux.

2023-07-26 08:56 UTC, LouisValery commented on public/questions/meteo/carte_meteo/lecture_carte.md
> +<small>Source : [*Cours théorique planche à voile*, Les Glénans CEB, 2023](https://encadrementbenevole.glenans.asso.fr/wp-content/uploads/2023/07/Cours-theorique-PAV-Version-1.pdf) </small>
heu... Longue histoire, j'essaye de les supprimer

2023-07-31 17:15 UTC, Dromadon approved these changes

2023-07-31 17:16 UTC, merged