Add new questions
Dromadon/gennaker pull request #7
Opened 2023-07-12 17:02 UTC by LouisValery

2023-07-16 10:19 UTC, Dromadon requested changes
Merci pour cette contrib, je t'ai laissé des commentaires sur quelques questions, et sur la stratégie de catégorisation qu'on adopte.

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/carte_meteo/determination_vitesse_vent.md
> +# Determiner la vitesse du vent � l'emplacement de l'�toile sur la carte m�t�o ci-dessous
Vu les soucis d'encodage, je soupçonne que ton Windows soit par défaut en encodage cp1252 (équivalent latin-1/latin-9) et pas en utf-8. Il faudrait que tu mettes ça à jour pour les fichiers avec accent.

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/carte_meteo/determination_vitesse_vent.md
> +# Answer
Je suis partagé sur cette question, car perso je ne le fait plus en N4 FFV. En voile légère, ça a peu d'intérêt je trouve, en croisière avec du large oui mais en VL je ne connais aucun moment où on utilise cette abaque.

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/carte_meteo/determiner_direction_du_vent.md
> +![image_question](./images/carte_vierge_calcul_vitesse.png)
Il faut qu'on mette un lien vers la source du metoffice. Leur site autorise explicitement la libre réutilisation, à condition qu'on se déclare (ce que je dois encore faire). 

La mention à poser est  : 
```
Data supplied by the Met Office
© British Crown copyright [followed by year], the Met Office
```

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/carte_meteo/determiner_direction_du_vent.md
> +![image_question](./images/carte_vierge_calcul_vitesse.png)
Je me dis que comme pour balises cardinales, on pourrait faire 3/4 versions de cette question pour avoir de la variabilité

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/phenomenes_macro/circulation_generale/cellule_ferrel.md
> +## Correction
La question me paraît trop peu précise pour que des stagiaires trouvent la réponse seuls.

Je trouve aussi le niveau trop avancé/détaillé pour le N4 FFV, surtout en voile légère. On n'a pas le temps de détailler les différentes cellules, juste de faire une présentation d'ensemble.

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/phenomenes_macro/circulation_generale/cellule_ferrel.md
> +## Correction
Je suis pour enlever la question.

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/phenomenes_macro/perturbation/vie_depression.md
> +![image_correction](./images/perturbation.png)
Je ne vois pas cette image ?

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/phenomenes_macro/perturbation/vie_depression.md
> +Création du front chaud : L’air chaud, en progressant vers le Nord, se confronte à la masse d'air froid. Comme il est plus léger que l'air froid, il va "contourner l'obstacle" en passant au-dessus. L
"détaillé plus tard dans ce chapitre" -> à enlever

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/phenomenes_macro/perturbation/vie_depression.md
> +L'air froid, plus dense, circule plus vite que l'air chaud. Le front froid rattrape donc petit à petit le front chaud. Il faut environ 24 heures pour que la liaison entre les deux fronts se réalise.
On n'évoque pas le décalage du point triple par rapport au centre dépressionnaire, qui est un indice d'une dépression assez vieille et qui devrait commencer à se combler.

J'enlèverais toute la partie sur le mécanisme de naissance des fronts ici.

2023-07-16 10:19 UTC, Dromadon commented on public/questions/meteo/phenomenes_macro/perturbation/passage_perturbation.md
> +Un schema complet peu suffire.
peut

2023-07-16 10:19 UTC, Dromadon commented on public/questions/technologie/divers/VL/windsurf/choix_aileron.md
> +Le volume de la planche: Plus une planche est volumineuse plus il lui faut un grand aileron. Ceci s'explique principalement par la planche peut atteindre: La force antidérive qu'un aileron génère éta
il manque un mot : "par la [??? que] la planche peut atteindre

2023-07-24 09:28 UTC, LouisValery commented
Outdated

2023-07-24 09:28 UTC, closed without merging